server:
  port: 8081

spring:
  application:
    name: m1
  sleuth:
    async:
      configurer:
        enabled: true
    sampler:
      percentage: 1.0
#    rxjava:
#      schedulers:
#        ignoredthreads:
#          -HystrixMetricPoller
#          -^RxComputation.*$
#          -elo-*